const assert=require('node:assert/strict'),vm=require('node:vm');
const {read}=require('./helpers/client.cjs');
const context=vm.createContext({URL,URLSearchParams,Request,Response,Headers,AbortSignal,Date,console,setTimeout,clearTimeout,fetch:async()=>Response.json({data:[]})});
const template=read('worker/index.template.js');
vm.runInContext(template.slice(template.indexOf('const API_BASE')).replace('__MOVEMENT_SERVER__',read('worker/movement.js')).replace('__LIVE_SERVER__',read('worker/live.js')).replace('__STATS_SHARED__',read('dist/stats.js')).replace('__RECORDS_SERVER__',read('worker/records.js')).replace('__ACCOUNTS_SERVER__',read('worker/accounts.js')).replace('export default {','this.worker={'),context);
const run=code=>vm.runInContext(code,context);
run('var originalSettle=settlePublicRecords,originalRecordStats=recordPlayerStats');
(async()=>{
  run(`var finishJob,started=0,background=[];
    settlePublicRecords=()=>{started++;return new Promise(resolve=>finishJob=resolve)};
    captureClosingLines=async()=>{};
    var env={BALLDONTLIE_API_KEY:'fixture',DB:{prepare:()=>({all:async()=>({results:[]})})}};
    var ctx={waitUntil:promise=>background.push(promise)};`);
  const response=await Promise.race([run('publicRecord(new Request("https://test.invalid/api/record"),env,ctx)'),new Promise((_,reject)=>setTimeout(()=>reject(Error('record read blocked on provider')),100))]);
  assert.equal(response.status,200);
  assert.equal(run('started'),1);
  run('queueRecordMaintenance(env,ctx)');assert.equal(run('started'),1,'concurrent visitors share grading');
  run('finishJob()');await Promise.all(run('background'));
  run('queueRecordMaintenance(env,ctx)');assert.equal(run('started'),1,'refreshes respect cooldown');
  run(`var lookupCount=0;recordPlayerStats=async()=>{lookupCount++;return {passing_yards:300,rushing_yards:20,game:{status_state:'final'}}};var shared=new Map();`);
  const results=await run(`Promise.all(['Passing Yards','Rushing Yards'].map(market=>gradePublicRecord({kind:'prop',player:'Player',gameTime:'2026-09-20T17:00:00Z',market,side:'Over',line:10},{},shared)))`);
  assert.deepEqual(Array.from(results),['won','won']);assert.equal(run('lookupCount'),1,'same player game shares one provider lookup across markets');
  run(`var observed={kind:'prop',player:'Player',gameTime:'2026-09-20T17:00:00Z',market:'Passing Yards',side:'Under',line:250.5};
    var observedCache=new Map([['Player|2026-09-20T17:00:00Z|Passing Yards',{passing_yards:200,game:{id:77,date:'2026-09-20T17:00:00Z',status_state:'in_progress'}}]]);
    bdlRequest=async()=>({data:[{id:77,status_state:'final'}]});`);
  assert.equal(await run('gradePublicRecord(observed,{BALLDONTLIE_API_KEY:"fixture"},observedCache)'),null,'scoreboard final alone is not confirmed box score');
  assert.equal(run('observed.provisionalResult'),'won','finished scoreboard permits provisional under win');
  run(`var first=recordSettlementState({status:'pending'},observed,null,1000000);var prior={status:first.status,result:first.result,legs:first.legs};`);
  assert.equal(run('first.status'),'provisional');
  assert.equal(run('recordSettlementState(prior,observed,null,2000000).status'),'provisional','time alone cannot confirm');
  run('observed.gradedLegs[0].boxScoreFinal=true;var finalCheck=recordSettlementState(prior,observed,"won",2000000);prior={status:finalCheck.status,result:finalCheck.result,legs:finalCheck.legs}');
  assert.equal(run('recordSettlementState(prior,observed,"won",2001000).status'),'provisional','requires repeat unchanged provider final');
  assert.equal(run('recordSettlementState(prior,observed,"won",2300000).status'),'final','matching final stats confirm after five minutes');
  run('observed.gradedLegs[0].actualValue=300;observed.gradedLegs[0].result="lost";observed.provisionalResult="lost"');
  assert.equal(run('recordSettlementState(prior,observed,"lost",2300000).status'),'provisional','correction restarts confirmation');
  assert.equal(run('recordSettlementState(prior,observed,"lost",2300000).result'),'lost','correction can reverse provisional winner');
  run('bdlRequest=async()=>({data:[{id:77,status_state:"in_progress"}]});observedCache.delete("scoreboard|2026-09-20")');
  await run('gradePublicRecord(observed,{BALLDONTLIE_API_KEY:"fixture"},observedCache)');
  assert.equal(run('observed.provisionalResult'),null,'unfinished game cannot create under win');
  // Exercise the real selection SQL, saved game metadata, grouped provider
  // calls and writes for a parlay whose last leg is tomorrow.
  const {DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(':memory:');
  for(const file of ['0000_public_record.sql','0001_record_settlement.sql','0002_historical_replays.sql'])db.exec(read('drizzle/'+file));
  const kickoff=new Date(Date.now()-6*3600000).toISOString(),tomorrow=new Date(Date.now()+24*3600000).toISOString();
  const leg={player:'Brian Thomas Jr.',sport:'NFL',market:'Receiving Yards',side:'Over',line:100.5,gameTime:kickoff,team:'Away Team · @ Home Team'};
  const insert=db.prepare("INSERT INTO public_recommendations(id,kind,player,market,side,line,game_time,legs_json,posted_at,source) VALUES(?,?,?,?,?,?,?,?,?,'market-verified-v2')");
  insert.run('future-parlay','parlay',null,null,null,null,tomorrow,JSON.stringify([leg,{...leg,player:'Future Player',gameTime:tomorrow}]),kickoff);
  insert.run('individual','prop',leg.player,leg.market,leg.side,leg.line,kickoff,JSON.stringify([leg]),kickoff);
  context.batchEnv={BALLDONTLIE_API_KEY:'fixture',DB:{prepare(sql){
    const stmt=db.prepare(sql);
    return {bind(...values){return {all:async()=>({results:stmt.all(...values)}),run:async()=>stmt.run(...values)}}};
  }}};
  context.fixtureGame={id:77,date:kickoff,status_state:'final',home_team:{full_name:'Home Team'},visitor_team:{full_name:'Away Team'}};
  run(`var providerCalls=[];recordPlayerStats=originalRecordStats;bdlRequest=async path=>{providerCalls.push(path);return path.startsWith('/nfl/v1/games?')?{data:[fixtureGame]}:{data:[{game:fixtureGame,player:{first_name:'Brian',last_name:'Thomas'},receiving_yards:20}]}}`);
  await run('originalSettle(batchEnv)');
  const checked=db.prepare('SELECT * FROM public_recommendations ORDER BY id').all();
  assert.deepEqual(checked.map(r=>[r.id,r.status,r.result]),[['future-parlay','provisional','lost'],['individual','provisional','lost']]);
  assert.equal(run('providerCalls.length'),2,'one scoreboard and one box score grade both picks');
  assert.equal(JSON.parse(checked[0].legs_json)[1].pendingReason,'Game not started');
  run(`var td={kind:'prop',player:'Player',gameTime:'2026-09-20T17:00:00Z',market:'Anytime Touchdown',side:'Over',line:.5};var tdCache=new Map([['Player|2026-09-20T17:00:00Z|Anytime Touchdown',{rushing_touchdowns:1,receiving_touchdowns:null,game:{status_state:'final'}}]])`);
  assert.equal(await run('gradePublicRecord(td,{},tdCache)'),'won','a reported scoring TD proves an anytime hit without invented zeros');
  assert.equal(run('td.gradedLegs[0].minimumOnly'),true);
  run('tdCache.set("Player|2026-09-20T17:00:00Z|Anytime Touchdown",{rushing_touchdowns:0,game:{status_state:"final"}})');
  assert.equal(await run('gradePublicRecord(td,{},tdCache)'),null,'missing scoring categories cannot prove a no-TD loss');
  run(`var scoringPlay={scoring_play:true,type_slug:'passing-touchdown',text:'Touchdown',participants:[{player_id:7,type:'passer'},{player_id:10,type:'receiver'}],team:{full_name:'Home Team'}};
    bdlRequest=async path=>path.startsWith('/nfl/v1/plays?')?{data:[scoringPlay],meta:{}}:{data:[]};
    var playRow={player_id:10,game:{id:77,status_state:'final'},scoreboardFinal:true};
    var firstTd={kind:'prop',player:'Scorer',gameTime:'2026-09-20T17:00:00Z',market:'First Touchdown',side:'Over',line:.5};
    var firstCache=new Map([['Scorer|2026-09-20T17:00:00Z|First Touchdown',playRow]]);`);
  assert.equal(await run('gradePublicRecord(firstTd,{BALLDONTLIE_API_KEY:"fixture"},firstCache)'),'won','play-by-play grades the first touchdown scorer');
  run(`var missTd={kind:'prop',player:'Non Scorer',gameTime:'2026-09-20T17:00:00Z',market:'Anytime Touchdown',side:'Over',line:.5};
    var missCache=new Map([['Non Scorer|2026-09-20T17:00:00Z|Anytime Touchdown',{...playRow,player_id:11}]]);`);
  assert.equal(await run('gradePublicRecord(missTd,{BALLDONTLIE_API_KEY:"fixture"},missCache)'),'lost','complete play-by-play grades a non-scorer as a loss');
  run(`var passerTd={kind:'prop',player:'Passer',gameTime:'2026-09-20T17:00:00Z',market:'Anytime Touchdown',side:'Over',line:.5};
    var passerCache=new Map([['Passer|2026-09-20T17:00:00Z|Anytime Touchdown',{...playRow,player_id:7}]]);`);
  assert.equal(await run('gradePublicRecord(passerTd,{BALLDONTLIE_API_KEY:"fixture"},passerCache)'),'lost','passing the touchdown does not count as scoring it');
  run(`var sackPlay={scoring_play:false,type_slug:'sack',type_text:'Sack',participants:[{player_id:12,type:'sacker'}]};
    var kickPlay={scoring_play:true,type_slug:'field-goal-good',type_text:'Field Goal',participants:[{player_id:13,type:'kicker'}]};
    bdlRequest=async path=>path.startsWith('/nfl/v1/plays?')?{data:[sackPlay,kickPlay],meta:{}}:{data:[]};
    var sackBet={kind:'prop',player:'Defender',gameTime:'2026-09-20T17:00:00Z',market:'Sacks',side:'Over',line:.5};
    var sackCache=new Map([['Defender|2026-09-20T17:00:00Z|Sacks',{player_id:12,game:{id:88,status_state:'final'},scoreboardFinal:true}]]);
    var kickBet={kind:'prop',player:'Kicker',gameTime:'2026-09-20T17:00:00Z',market:'Kicking Points',side:'Over',line:2.5};
    var kickCache=new Map([['Kicker|2026-09-20T17:00:00Z|Kicking Points',{player_id:13,game:{id:88,status_state:'final'},scoreboardFinal:true}]]);`);
  assert.equal(await run('gradePublicRecord(sackBet,{BALLDONTLIE_API_KEY:"fixture"},sackCache)'),'won','play-by-play fills a missing sack total');
  assert.equal(await run('gradePublicRecord(kickBet,{BALLDONTLIE_API_KEY:"fixture"},kickCache)'),'won','play-by-play fills missing kicking points');
  assert.equal(run('BTGStats.metric({market:"Assists"},{total_tackles:9,solo_tackles:6}).value'),3,'assisted tackles derived from reported total and solo');
  console.log('PASS: responsive reads, provisional corrections, shared game box scores, pending Monday parlay loss, individual grading, touchdown evidence and assists');
})().catch(error=>{console.error(error);process.exitCode=1});
